version: '3'
services:
  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.6.0
    container_name: wazuh.indexer
    networks:
      - wazuh-network
    security_opt:
      - apparmor:unconfined
    dns: 172.23.0.53
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - INDEXER_PASSWORD=${WAZUH_INDEXER_PASS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ${WAZUH_ROOT}/wazuh-indexer-data:/var/lib/wazuh-indexer
      - ${WAZUH_ROOT}/config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - ${WAZUH_ROOT}/config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key
      - ${WAZUH_ROOT}/config/wazuh_indexer_ssl_certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      - ${WAZUH_ROOT}/config/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
      - ${WAZUH_ROOT}/config/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
      - ${WAZUH_ROOT}/config/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml
      - ${WAZUH_ROOT}/config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/opensearch-security/internal_users.yml
  wazuh.manager:
    image: wazuh/wazuh-manager:4.6.0
    container_name: wazuh.manager
    networks:
      - wazuh-network
    dns: 172.23.0.53
    restart: always
    security_opt:
      - apparmor:unconfined
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=${WAZUH_INDEXER_USER}
      - INDEXER_PASSWORD=${WAZUH_INDEXER_PASS}
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=${WAZUH_API_USER}
      - API_PASSWORD=${WAZUH_API_PASS}
    volumes:
      - ${WAZUH_ROOT}/wazuh_api_configuration:/var/ossec/api/configuration
      - ${WAZUH_ROOT}/wazuh_etc:/var/ossec/etc
      - ${WAZUH_ROOT}/wazuh_logs:/var/ossec/logs
      - ${WAZUH_ROOT}/wazuh_queue:/var/ossec/queue
      - ${WAZUH_ROOT}/wazuh_var_multigroups:/var/ossec/var/multigroups
      - ${WAZUH_ROOT}/wazuh_integrations:/var/ossec/integrations
      - ${WAZUH_ROOT}/wazuh_active_response:/var/ossec/active-response/bin
      - ${WAZUH_ROOT}/wazuh_agentless:/var/ossec/agentless
      - ${WAZUH_ROOT}/wazuh_wodles:/var/ossec/wodles
      - ${WAZUH_ROOT}/filebeat_etc:/etc/filebeat
      - ${WAZUH_ROOT}/filebeat_var:/var/lib/filebeat
      - ${WAZUH_ROOT}/config/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ${WAZUH_ROOT}/config/wazuh_indexer_ssl_certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
      - ${WAZUH_ROOT}/config/wazuh_indexer_ssl_certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key
      - ${WAZUH_ROOT}/config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf
  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.6.0
    container_name: wazuh.dashboard
    restart: always
    dns: 172.23.0.53
    security_opt:
      - apparmor:unconfined
    networks:
      - wazuh-network
    ports:
      - 5601:5601
    environment:
      - INDEXER_USERNAME=${WAZUH_INDEXER_USER}
      - INDEXER_PASSWORD=${WAZUH_INDEXER_PASS}
      - WAZUH_API_URL=https://wazuh.manager
      - DASHBOARD_USERNAME=${WAZUH_DASH_USER}
      - DASHBOARD_PASSWORD=${WAZUH_DASH_PASS}
      - API_USERNAME=${WAZUH_API_USER}
      - API_PASSWORD=${WAZUH_API_PASS}
    volumes:
      - ${WAZUH_ROOT}/config/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - ${WAZUH_ROOT}/config/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - ${WAZUH_ROOT}/config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - ${WAZUH_ROOT}/config/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - ${WAZUH_ROOT}/config/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
      - ${WAZUH_ROOT}/wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
      - ${WAZUH_ROOT}/wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
    depends_on:
      - wazuh.indexer
    links:
      - wazuh.indexer:wazuh.indexer
      - wazuh.manager:wazuh.manager

networks:
  wazuh-network:
    name: wazuh-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24